---
title: Boundless
timezone: America/Phoenix
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: info@getboundless.com
description: Boundless
baseurl: ""
url: ""
twitter_username: ""
github_username: ""
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
