---
title: Boundless
timezone: America/Phoenix
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
url: http://boundless.siteleaf.net
email: info@getboundless.com
description: Boundless
markdown_ext: markdown,mkdown,mkdn,mkd,md
markdown: kramdown
sass:
  style: compressed
autoprefixer:
  browsers:
  - last 2 versions
highlighter: rouge
include:
- _pages
- Gemfile
- Gemfile.lock
exclude:
- node_modules
- README.md
plugins:
- jekyll-autoprefixer
gems:
- jekyll-feed
permalink: pretty
sass:
  sass_dir: css